### ISSUE TITLE
Floating listings in LTXexample environment

### ISSUE THREAD

**Issue by koppor** [rolfn/showexpl#1]
Background: I am working on a [latex template generator](https://github.com/latextemplates/generator-latex-template) which generates a template with minimal working examples for each package used. I made the experience that students read the PDF first and then look at the LaTeX code. They are not experienced in using two tools for seeing the LaTeX code and the PDF. Thus, it is hard for them to get the result of the LaTeX code. Thus, I aim for providing the LaTeX code side-by-side with the compilation output. This package is a good fit for it. -- I also want to include the minimal working examples in a full `.tex` file, where the students can start LaTeXing and experimenting with the MWEs.

I tried following document:

```latex
\documentclass{scrbook}

\usepackage{listings}
\usepackage{showexpl}

\begin{document}

\begin{LTXexample}
\begin{lstlisting}[
  language=XML,
  float,
  caption={Example},
  label={lst:XML}]
<listing />
\end{lstlisting}
\end{LTXexample}

\end{document}
```

I get:

```text
! LaTeX Error: Not in outer par mode.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.5   label={lst:XML}]
```

I wonder how can I a) show the label and the caption in the compiled output and b) use the lstlisting environment as usual in the other parts of the document?

Note that it perfectly works with the figure environment:

```latex
\begin{LTXexample}
\begin{figure}
Hello
\caption{Float}
\label{fig:float}
\end{figure}
\end{LTXexample}
```

**Comment by koppor** [comment]
With latest master (https://github.com/rolfn/showexpl/commit/577625270f7129e5d2d1d7119c63fa855ad9cd44), it compiles. Thank you for the update.

When having following LaTeX code:

```latex
\documentclass{article}

\usepackage{cleveref}
\usepackage{showexpl}

\begin{document}

\Cref{fig:float} shows something.

\begin{LTXexample}
\begin{figure}
Hello
\caption{Float}
\label{fig:float}
\end{figure}
\end{LTXexample}

\end{document}
```

I get following output:

![grafik](https://user-images.githubusercontent.com/1366654/81013077-e0ec3a00-8e5a-11ea-808a-ac4444902cfa.png)

I would have expected that the label still works.

**Comment by rolfn** [comment]
I will copy the new version to CTAN shortly.
