### ISSUE TITLE
missing enumerate items

### ISSUE THREAD

**Issue by sje30** [rolfn/showexpl#10]
Hi,
any ideas why the enumerate numbers are all set to 0. here rather than 1 2 3 ?

```
\documentclass{article}
\usepackage{showexpl}
\begin{document}

minimal example

\begin{LTXexample}
  \textbf{Top TV programmes}:
  \begin{enumerate}
  \item Homeland
  \item The West Wing
  \item 24
  \end{enumerate}
\end{LTXexample}
\end{document}

```

[o.pdf](https://github.com/rolfn/showexpl/files/5320423/o.pdf)

**Comment by rolfn** [comment]
Yes, that was a stupid mistake. I have corrected it in the current version (0.3r). Thanks for the bug report.
