### ISSUE TITLE
LTXexample infinite loop with cleveref and algorithm

### ISSUE THREAD

**Issue by michaliskok** [rolfn/showexpl#11]
Hello,

Recent versions of the package broke code like the following:

```
\documentclass{article}
\usepackage{algorithm}
\usepackage{algpseudocode}
\usepackage{cleveref}
\usepackage{showexpl}

\begin{document}

\begin{LTXexample}[wide,width=.5,preset=\footnotesize,rframe={},%
    codefile=\jobname-\theltxexample-alg.tex]
\begin{algorithm}[H]
\begin{algorithmic}[1]
\Procedure{Foo}{Bar}
\EndProcedure
\end{algorithmic}
\end{algorithm}
\end{LTXexample}

\end{document}
```

There seems to be an infinite loop when `cleveref` is used. I have not bisected the exact commit that introduced the breakage, but the code above is working fine with commit 577625270f7129e5d2d1d7119c63fa855ad9cd44.

Michalis

**Comment by rolfn** [comment]
Hello Michalis,
please test the current version (v0.3s). If it works, I'll copy it to CTAN. Thanks for the bug report.

Rolf

**Comment by michaliskok** [comment]
Hello, Rolf,

Thanks for the prompt reply. I tested v0.3s but it does not seem to work (for the same test case); I am attaching the relevant log.

Thank you,
Michalis

[demo.log](https://github.com/rolfn/showexpl/files/5769317/demo.log)

**Comment by rolfn** [comment]
You're right. Let's try again. I hope the current version works now.

**Comment by michaliskok** [comment]
Indeed, this version works! Thanks a lot!

**Comment by rolfn** [comment]
The new version is on the way to CTAN.
