### ISSUE TITLE
Referencing inside of an environment does not work

### ISSUE THREAD

**Issue by koppor** [rolfn/showexpl#5]
I would expect that referecing works inside the `LTXexample` environment.

MWE:

```latex
\documentclass{article}

\usepackage{cleveref}
\usepackage{showexpl}

\begin{document}

\begin{LTXexample}
\begin{figure}
Hello
\caption{Float}
\label{fig:float}
\end{figure}

\Cref{fig:float} shows something.

\end{LTXexample}

\end{document}
```

Output:

![grafik](https://user-images.githubusercontent.com/1366654/81105506-536d2080-8f14-11ea-879e-55d006392b64.png)

```tex
LaTeX Warning: Reference `fig:float' on page 1 undefined on input line 8.

LaTeX Warning: There were undefined references.
```

I would have not expected `??`.

**Comment by koppor** [comment]
For reference for interested readers: Rendered example with the (unmaintained) [examplep](https://ctan.org/pkg/examplep) package illustrating the aim...

I think, it is hard to implement and I am the only one requesting it. The workaround is not to use floats at all in examples. Use `[H]` from the float parameter, etc.

![grafik](https://user-images.githubusercontent.com/1366654/81216468-38b1af00-8fdb-11ea-9361-afd51140affc.png)

```latex
\documentclass{article}

\usepackage{cleveref}
\usepackage{listings}
\usepackage{examplep}

\begin{document}

\listoffigures

\begin{figure}[t]
    fig1
    \caption{fig1}
    \label{fig1}
\end{figure}

Are you fig1, \cref{fig1}?
  
\begin{WSample}

\listoffigures

\begin{figure}
fig2
\caption{fig2}
\label{fig2}
\end{figure}
Are you fig2, \cref{fig2}?
\ref{fig2}
\end{WSample}

\PexaShowBoth{}

\begin{figure}[b]
    fig3
    \caption{fig3}
    \label{fig3}
\end{figure}

Are you fig3, \cref{fig3}?

\end{document}
```

**Comment by koppor** [comment]
I'll close this as I will try with other packages.

**Comment by koppor** [comment]
Any chance to get this working? Seems to be complicated.

![grafik](https://user-images.githubusercontent.com/1366654/82844900-8c306200-9ee2-11ea-858f-88b9b39f2c92.png)

Refined "MWE":

```
\documentclass{book}

\usepackage{cleveref}
\usepackage{showexpl}

\begin{document}

\chapter{Chapter 1}

\listoffigures

\section{Section 1}

\begin{figure}
    Hello1
    \caption{Float1}
    \label{fig:float}
\end{figure}

Who am I \cref{fig:float}? You should be 1.1.

\begin{LTXexample}
\begin{figure}
Hello2
\caption{Float2}
\label{fig:float2}
\end{figure}

\Cref{fig:float2} shows something. You should be 1.1.

\end{LTXexample}

\section{Section 2}

\begin{figure}
    Hello3
    \caption{Float3}
    \label{fig:float3}
\end{figure}

Who am I \cref{fig:float3}? You should be 1.2.

\end{document}
```

**Comment by koppor** [comment]
With latest `master` (of today), I get

```text
! Undefined control sequence.
<argument> \@captype

l.31 \end{LTXexample}

?
! Emergency stop.
<argument> \@captype

l.31 \end{LTXexample}

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on main-showexpl.log.
```

**Comment by rolfn** [comment]
This was a bug of redefining floats within LTXexample. Should be corrected in the current version.

I will not support references from LTXexample to the outside and vice versa. The number caused by caption within LTXexample will always be zero.

**Comment by koppor** [comment]
Thank you! Will try later. I was asking from referencing inside (!) the LTXexmaple environment to a figure inside (!) the same (!) LTXemple environment. In other words: Referencing inside the same context. The above MWE provides such an example. Two floats outside LTXexample, referenced from outside. One float inside the LTXexmaple environment, referenced inside the same environment. - One float before, one float after the LTXexmaple environment to check for counters being increased correctly.

I can provide a more minimal example later.

**Comment by rolfn** [comment]
All label and ref commands inside LTXexample are switched off. Too complicated and too confusing.

**Comment by koppor** [comment]
OK. Then, I'll close the issue.

For the googlers: examplep and cnltx-example support that, but have other issues. See their bug trackers.
